$commands = @(
    # "python -u run_longExp.py --random_seed 2021 --is_training 1 --root_path ./dataset/weather/ --data_path weather.csv --model_id Weather_96_96 --model PatchTST --data custom --features M --seq_len 96 --pred_len 96 --enc_in 21 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_longExp.py --random_seed 2021 --is_training 1 --root_path ./dataset/weather/ --data_path weather.csv --model_id Weather_96_192 --model PatchTST --data custom --features M --seq_len 96 --pred_len 192 --enc_in 21 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_longExp.py --random_seed 2021 --is_training 1 --root_path ./dataset/weather/ --data_path weather.csv --model_id Weather_96_336 --model PatchTST --data custom --features M --seq_len 96 --pred_len 336 --enc_in 21 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_longExp.py --random_seed 2021 --is_training 1 --root_path ./dataset/weather/ --data_path weather.csv --model_id Weather_96_720 --model PatchTST --data custom --features M --seq_len 96 --pred_len 720 --enc_in 21 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --itr 1 --batch_size 512 --learning_rate 0.0001",

    
    "python -u run_longExp.py --is_training 1 --random_seed 2021 --root_path ./dataset/exchange_rate/ --data_path exchange_rate.csv --model_id Exchange_96_96 --model PatchTST --data custom --features M --seq_len 96 --pred_len 96 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --d_layers 1 --factor 3 --enc_in 8 --dec_in 8 --c_out 8 --des 'Exp' --itr 1 --batch_size 512 --train_epochs 10 --patience 3 --learning_rate 0.0001",
    "python -u run_longExp.py --is_training 1 --random_seed 2021 --root_path ./dataset/exchange_rate/ --data_path exchange_rate.csv --model_id Exchange_96_192 --model PatchTST --data custom --features M --seq_len 96 --pred_len 192 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --d_layers 1 --factor 3 --enc_in 8 --dec_in 8 --c_out 8 --des 'Exp' --itr 1 --batch_size 512 --train_epochs 10 --patience 3 --learning_rate 0.0001",
    "python -u run_longExp.py --is_training 1 --random_seed 2021 --root_path ./dataset/exchange_rate/ --data_path exchange_rate.csv --model_id Exchange_96_336 --model PatchTST --data custom --features M --seq_len 96 --pred_len 336 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --d_layers 1 --factor 3 --enc_in 8 --dec_in 8 --c_out 8 --des 'Exp' --itr 1 --batch_size 256 --train_epochs 10 --patience 3 --learning_rate 0.0001",
    "python -u run_longExp.py --is_training 1 --random_seed 2021 --root_path ./dataset/exchange_rate/ --data_path exchange_rate.csv --model_id Exchange_96_720 --model PatchTST --data exchange_high --features M --seq_len 96 --pred_len 720 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --d_layers 1 --factor 3 --enc_in 8 --dec_in 8 --c_out 8 --des 'Exp' --itr 1 --batch_size 128 --train_epochs 10 --patience 3 --learning_rate 0.0001"
    
    # "python -u run_longExp.py --is_training 1 --root_path ./dataset/ETT-small/ --data_path ETTm2.csv --model_id ETTm2_96_96 --model PatchTST --data ETTm2  --n_heads 16 --features M --seq_len 96 --pred_len 96 --e_layers 3 --d_layers 1 --factor 3 --enc_in 7 --dec_in 7 --c_out 7 --des 'Exp' --itr 1 --batch_size 512 --train_epochs 10",
    # "python -u run_longExp.py --is_training 1 --root_path ./dataset/ETT-small/ --data_path ETTm2.csv --model_id ETTm2_96_192 --model PatchTST --data ETTm2 --n_heads 16 --features M --seq_len 96 --pred_len 192 --e_layers 3 --d_layers 1 --factor 3 --enc_in 7 --dec_in 7 --c_out 7 --des 'Exp' --itr 1 --batch_size 512 --train_epochs 10",
    # "python -u run_longExp.py --is_training 1 --root_path ./dataset/ETT-small/ --data_path ETTm2.csv --model_id ETTm2_96_336 --model PatchTST --data ETTm2 --n_heads 16 --features M --seq_len 96 --pred_len 336 --e_layers 3 --d_layers 1 --factor 3 --enc_in 7 --dec_in 7 --c_out 7 --des 'Exp' --itr 1 --batch_size 512 --train_epochs 10",
    # "python -u run_longExp.py --is_training 1 --root_path ./dataset/ETT-small/ --data_path ETTm2.csv --model_id ETTm2_96_720 --model PatchTST --data ETTm2 --n_heads 16 --features M --seq_len 96 --pred_len 720 --e_layers 3 --d_layers 1 --factor 3 --enc_in 7 --dec_in 7 --c_out 7 --des 'Exp' --itr 1 --batch_size 512 --train_epochs 10"
    
    # "python -u run_longExp.py --random_seed 2021 --is_training 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96 --model PatchTST --data ETTm2 --features M --seq_len 96 --pred_len 96 --enc_in 7 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --lradj 'TST' --pct_start 0.4 --itr 1 --batch_size 512 --learning_rate 0.0001"
    # "python -u run_longExp.py --random_seed 2021 --is_training 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_192 --model PatchTST --data ETTm2 --features M --seq_len 96 --pred_len 192 --enc_in 7 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --lradj 'TST' --pct_start 0.4 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_longExp.py --random_seed 2021 --is_training 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_336 --model PatchTST --data ETTm2 --features M --seq_len 96 --pred_len 336 --enc_in 7 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --lradj 'TST' --pct_start 0.4 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_longExp.py --random_seed 2021 --is_training 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_720 --model PatchTST --data ETTm2 --features M --seq_len 96 --pred_len 720 --enc_in 7 --e_layers 3 --n_heads 16 --d_model 128 --d_ff 256 --dropout 0.2 --fc_dropout 0.2 --head_dropout 0 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --lradj 'TST' --pct_start 0.4 --itr 1 --batch_size 512 --learning_rate 0.0001"
)
# Eksekusi setiap perintah dan hentikan jika ada error
foreach ($cmd in $commands) {
    Write-Host "Running: $cmd"
    Invoke-Expression $cmd
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Error encountered, stopping script."
        exit $LASTEXITCODE
    }
}

Write-Host "All models have been trained successfully."