$commands = @(
    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/weather/ --data_path weather.csv --model_id weatherACLR_NEWALGO_96_96 --use_aclr --model FRNet --data custom --features M --seq_len 96 --pred_len 96 --enc_in 21 --e_layers 2 --n_heads 8 --d_model 64 --d_ff 128 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 25 --lradj type1 --pred_head_type 'linear' --aggregation_type 'linear' --channel_attention 0 --global_freq_pred 0 --period_list 72 --emb 164 --decomposition 0 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/weather/ --data_path weather.csv --model_id weatherACLR_NEWALGO_96_192 --use_aclr --model FRNet --data custom --features M --seq_len 96 --pred_len 192 --enc_in 21 --e_layers 2 --n_heads 8 --d_model 64 --d_ff 128 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 25 --lradj type1 --pred_head_type 'linear' --aggregation_type 'linear' --channel_attention 0 --global_freq_pred 0 --period_list 72 --emb 164 --decomposition 0 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/weather/ --data_path weather.csv --model_id weatherACLR_NEWALGO_96_336 --use_aclr --model FRNet --data custom --features M --seq_len 96 --pred_len 336 --enc_in 21 --e_layers 2 --n_heads 8 --d_model 64 --d_ff 128 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 25 --lradj type1 --pred_head_type 'linear' --aggregation_type 'linear' --channel_attention 0 --global_freq_pred 0 --period_list 72 --emb 164 --decomposition 0 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/weather/ --data_path weather.csv --model_id weatherACLR_NEWALGO_96_720 --use_aclr --model FRNet --data custom --features M --seq_len 96 --pred_len 720 --enc_in 21 --e_layers 2 --n_heads 8 --d_model 64 --d_ff 128 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 25 --lradj type1 --pred_head_type 'linear' --aggregation_type 'linear' --channel_attention 0 --global_freq_pred 0 --period_list 72 --emb 164 --decomposition 0 --itr 1 --batch_size 512 --learning_rate 0.0001",

    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/exchange_rate/ --data_path exchange_rate.csv --model_id exchangeACLR_NEWALGO_96_96 --use_aclr --model FRNet --data custom --features M --seq_len 96 --pred_len 96 --enc_in 8 --dec_in 8 --c_out 8 --e_layers 2 --n_heads 8 --d_model 128 --d_ff 128 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 25 --lradj type1 --pred_head_type 'linear' --aggregation_type 'linear' --channel_attention 0 --global_freq_pred 0 --period_list 72 --emb 164 --decomposition 0 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/exchange_rate/ --data_path exchange_rate.csv --model_id exchangeACLR_NEWALGO_96_192 --use_aclr --model FRNet --data custom --features M --seq_len 96 --pred_len 192 --enc_in 8 --dec_in 8 --c_out 8 --e_layers 2 --n_heads 8 --d_model 128 --d_ff 128 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 25 --lradj type1 --pred_head_type 'linear' --aggregation_type 'linear' --channel_attention 0 --global_freq_pred 0 --period_list 72 --emb 164 --decomposition 0 --itr 1 --batch_size 512 --learning_rate 0.0001",
    "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/exchange_rate/ --data_path exchange_rate.csv --model_id exchangeACLRHANDLENAN_NEWALGO_96_336 --use_aclr --model FRNet --data custom --features M --seq_len 96 --pred_len 336 --enc_in 8 --dec_in 8 --c_out 8 --e_layers 2 --n_heads 8 --d_model 128 --d_ff 128 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 25 --lradj type1 --pred_head_type 'linear' --aggregation_type 'linear' --channel_attention 0 --global_freq_pred 0 --period_list 72 --emb 164 --decomposition 0 --itr 1 --batch_size 256 --learning_rate 0.0001",
    "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/exchange_rate/ --data_path exchange_rate.csv --model_id exchangeACLRHANDLENAN_NEWALGO_96_720 --use_aclr --model FRNet --data exchange_high --features M --seq_len 96 --pred_len 720 --enc_in 8 --dec_in 8 --c_out 8 --e_layers 2 --n_heads 8 --d_model 128 --d_ff 128 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 25 --lradj type1 --pred_head_type 'linear' --aggregation_type 'linear' --channel_attention 0 --global_freq_pred 0 --period_list 72 --emb 164 --decomposition 0 --itr 1 --batch_size 128 --learning_rate 0.0001"

    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2ACLR_NEWALGO_96_96 --use_aclr --model FRNet --data ETTm2 --features M --seq_len 96 --pred_len 96 --enc_in 7 --e_layers 1 --n_heads 8 --d_model 128 --d_ff 256 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 97 --lradj type1 --pred_head_type 'linear' --aggregation_type 'avg' --channel_attention 0 --global_freq_pred 1 --period_list 96 --emb 96 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2ACLR_NEWALGO_96_192 --use_aclr --model FRNet --data ETTm2 --features M --seq_len 96 --pred_len 192 --enc_in 7 --e_layers 1 --n_heads 8 --d_model 128 --d_ff 256 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 97 --lradj type1 --pred_head_type 'linear' --aggregation_type 'avg' --channel_attention 0 --global_freq_pred 1 --period_list 96 --emb 96 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2ACLR_NEWALGO_96_336 --use_aclr --model FRNet --data ETTm2 --features M --seq_len 96 --pred_len 336 --enc_in 7 --e_layers 1 --n_heads 8 --d_model 128 --d_ff 256 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 97 --lradj type1 --pred_head_type 'linear' --aggregation_type 'avg' --channel_attention 0 --global_freq_pred 1 --period_list 96 --emb 96 --itr 1 --batch_size 512 --learning_rate 0.0001",
    # "python -u run_newalgo.py --random_seed 2021 --is_training 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2ACLR_NEWALGO_96_720 --use_aclr --model FRNet --data ETTm2 --features M --seq_len 96 --pred_len 720 --enc_in 7 --e_layers 1 --n_heads 8 --d_model 128 --d_ff 256 --dropout 0.1 --fc_dropout 0.1 --head_dropout 0.1 --patch_len 16 --stride 8 --des 'Exp' --train_epochs 10 --patience 3 --kernel_size 97 --lradj type1 --pred_head_type 'linear' --aggregation_type 'avg' --channel_attention 0 --global_freq_pred 1 --period_list 96 --emb 96 --itr 1 --batch_size 512 --learning_rate 0.0001"
)

# Eksekusi setiap perintah dan hentikan jika ada error
foreach ($cmd in $commands) {
    Write-Host "Running: $cmd"
    Invoke-Expression $cmd
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Error encountered, stopping script."
        exit $LASTEXITCODE
    }
}

Write-Host "All models have been trained successfully."